/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Oto;

import javax.swing.JOptionPane;

/**
 *
 * @author marc
 */
public class BeforeGame extends javax.swing.JPanel {

    GameBoy gameBoy;
    
    /**
     * Creates new form History
     */
    public BeforeGame() {
        initComponents();
    }

    BeforeGame(GameBoy gameBoy) {
        this();
        this.gameBoy = gameBoy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCamada1_BeforeGame = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JButton();
        ButtonHighscore = new javax.swing.JButton();
        ButtonHelp = new javax.swing.JButton();
        ButtonAbout = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(320, 180));

        panelCamada1_BeforeGame.setBackground(new java.awt.Color(0, 0, 0));
        panelCamada1_BeforeGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));

        buttonPlay.setBackground(new java.awt.Color(0, 0, 0));
        buttonPlay.setForeground(new java.awt.Color(255, 255, 255));
        buttonPlay.setText("PLAY");
        buttonPlay.setAutoscrolls(true);
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        ButtonHighscore.setText("HIGH SCORE");

        ButtonHelp.setText("HELP");

        ButtonAbout.setBackground(new java.awt.Color(0, 0, 0));
        ButtonAbout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAbout.setText("ABOUT");
        ButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamada1_BeforeGameLayout = new javax.swing.GroupLayout(panelCamada1_BeforeGame);
        panelCamada1_BeforeGame.setLayout(panelCamada1_BeforeGameLayout);
        panelCamada1_BeforeGameLayout.setHorizontalGroup(
            panelCamada1_BeforeGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamada1_BeforeGameLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(panelCamada1_BeforeGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonHighscore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(ButtonAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        panelCamada1_BeforeGameLayout.setVerticalGroup(
            panelCamada1_BeforeGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamada1_BeforeGameLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(buttonPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonHighscore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAbout)
                .addGap(169, 169, 169))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCamada1_BeforeGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCamada1_BeforeGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        
        gameBoy.startHistory();
        
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void ButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAboutActionPerformed
        
        JOptionPane.showConfirmDialog(this, "Developed for us --> [DiegoBoy], [Eu], [Nininho] and [Stealth] ... ", "Informations", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_ButtonAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAbout;
    private javax.swing.JButton ButtonHelp;
    private javax.swing.JButton ButtonHighscore;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JPanel panelCamada1_BeforeGame;
    // End of variables declaration//GEN-END:variables
}
