/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Oficial;

/**
 *
 * @author kratos
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        painelLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 1, 1));
        setLayout(new java.awt.BorderLayout());

        painelBotoes.setBackground(new java.awt.Color(0, 0, 0));
        painelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "D.L.O.L Entertainment", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(93, 93, 93));
        jButton1.setText("PLAY");
        painelBotoes.add(jButton1);

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(93, 93, 93));
        jButton2.setText("HIGH SCORE");
        painelBotoes.add(jButton2);

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(93, 93, 93));
        jButton3.setText("HELP");
        painelBotoes.add(jButton3);

        jButton4.setBackground(new java.awt.Color(254, 254, 254));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(93, 93, 93));
        jButton4.setText("ABOUT");
        painelBotoes.add(jButton4);

        add(painelBotoes, java.awt.BorderLayout.CENTER);

        painelLogo.setBackground(new java.awt.Color(1, 1, 1));
        painelLogo.setLayout(new java.awt.BorderLayout());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO.png"))); // NOI18N
        painelLogo.add(labelLogo, java.awt.BorderLayout.CENTER);

        add(painelLogo, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelLogo;
    // End of variables declaration//GEN-END:variables
}
